import Car from './cars';
import Colors from "./Colors";
import Directions from "./Directions";
import Doors from "./Doors";
const Gol = new Car("Volswagen",4, Colors.Silver);
Gol.openTheDoor(Doors.DRIVER);
Gol.closeTheDoor(Doors.DRIVER);
Gol.turnOn();
Gol.speedUp();
Gol.turn(Directions.LEFT);
Gol.turn(Directions.RIGHT);
Gol.turn(Directions.RIGHT);
Gol.speedDown();
Gol.stop();
Gol.openTheDoor(Doors.BEHIND_RIDE);
Gol.closeTheDoor(Doors.BEHIND_RIDE);
Gol.speedUp();
Gol.turn(Directions.RIGHT);
Gol.turn(Directions.LEFT);
Gol.turn(Directions.RIGHT);
Gol.speedDown();
Gol.stop();
Gol.turnOff();
Gol.openTheDoor(Doors.BEHIND_DRIVER);
Gol.closeTheDoor(Doors.BEHIND_DRIVER);
Gol.turnOn();
Gol.speedUp();